// Generated by CoffeeScript 1.6.2
(function() {
  var log,
    __slice = [].slice;

  log = function() {
    var args;

    args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    if ((typeof console !== "undefined" && console !== null ? console.log : void 0) != null) {
      return console.log.apply(console, args);
    }
  };

  $('#dragbar').mousedown(function(e) {
    e.preventDefault();
    $('#top-div, #bottom-div').append("<div class='over'></div>");
    log('dragging', e.pageY);
    return $(document).mousemove(function(e) {
      $('#top-div').css("height", e.pageY + 2);
      return $('#bottom-div').css("top", e.pageY + 2);
    });
  });

  $(document).mouseup(function(e) {
    $(document).unbind('mousemove');
    return $('.over').remove();
  });

  $('.cover').click(function(e) {
    $(this).css('opacity', '.5').animate({
      opacity: 0
    }, 3000);
    return false;
  });

}).call(this);
